nebracy/apps/views.py
from decimal import Decimal
from flask import Blueprint, render_template, redirect, session, url_for, request, abort
import math
from nebracy.apps.forms import DoughCalculatorForm


apps = Blueprint('apps', __name__, subdomain='app')


@apps.route('/', methods=['GET', 'POST'])
@apps.route('/pizza-dough-calculator', methods=['GET', 'POST'])
def pizza():
    form = DoughCalculatorForm(flour=100)
    if form.validate_on_submit():
        dough = {ing.name: {'Percent': ing.data} for ing in form if ing.description}

        for ing in form.opt.data + [form.yeast.data]:
            if ing['iname']:
                dough[ing['iname']] = {}
                dough[ing['iname']]['Percent'] = ing['num']

        if form.dough_wt.data and form.choice.data == 'Dough Weight':
            dough_wt = form.dough_wt.data
        else:
            radius2 = (form.pizza_size.data / 2) ** 2
            dough_wt = form.thk_factor.data * Decimal(math.pi * radius2)
        total_pct = sum(val['Percent'] for val in dough.values())
        flour_wt = dough_wt * form.pizza_num.data / (total_pct / 100)

        dough |= {'total': {'Percent': total_pct}}
        for kv in dough.values():
            weight = flour_wt * (kv['Percent']) / 100
            kv['Grams'] = kv['Ounces'] = weight
            if form.g_oz.data == 'g' and form.choice.data == 'Dough Weight':
                kv |= {'Ounces': weight * Decimal(0.03527396195)}
            else:
                kv |= {'Grams': weight * Decimal(28.349523125)}
        session['recipe'] = dough
        return redirect(url_for('apps.pizza', _external=True, _scheme='https', _anchor='recipe'))
    dough = total = None
    if recipe := session.get('recipe'):
        total = recipe.pop('total')
        list_order = ['flour', 'water', 'IDY', 'ADY', 'salt', 'olive_oil', 'sugar']
        list_order.extend(k for k in recipe.keys() - list_order)
        dough = {k: recipe[k] for k in list_order if recipe.get(k)}
    return render_template('apps/pizza.html', form=form, dough=dough, total=total)


@apps.get('/pizza-dough-calculator/add-ingredient')
@apps.get('/pizza-dough-calculator/add-ingredient/<int:opt_entry>')
def add_ingredient(opt_entry=0):
    if 'HX_request' not in request.headers:
        abort(400)

    form = DoughCalculatorForm()
    try:
        opt = form.opt.entries.pop(opt_entry)
    except IndexError:
        abort(404)
    else:
        opt_entry += 1
        return render_template('apps/add.html', opt=opt, opt_entry=opt_entry, max_opt=form.opt.max_entries)

nebracy/templates/apps/add.html
{% from "macros.html" import app_formfield %}

{{ app_formfield(opt, class='form-control', value=0, step=0.05) }}
{% if opt_entry < max_opt %}
    <div class="col-sm-4 d-inline-flex" hx-target="this" hx-swap="outerHTML">
        <button id="hx-add" class="btn btn-sm btn-outline-secondary col-auto my-1 me-2"
                hx-get="{{ url_for('apps.add_ingredient', opt_entry=opt_entry, _external=True, _scheme='https') }}"
                hx-trigger="click">Add Ingredient
        </button>
    </div>
{% else %}
    <div class="col-sm-4 d-inline-flex"></div>
{% endif %}

nebracy/templates/apps/pizza.html
{% extends "layout.html" %}
{% block title %}NY Style Pizza Dough Calculator{% endblock title %}
{% block desc %}
<meta name="description" content="This pizza dough calculator will help you make the perfect dough for a homemade New York-Style pizza.">
{% endblock desc %}
{% block script %}
<script defer src="{{ url_for('static', filename='js/apps.js', _external=True, _scheme='https') }}"></script>
<script defer src="https://unpkg.com/htmx.org@1.6.1/dist/htmx.min.js" integrity="sha384-tvG/2mnCFmGQzYC1Oh3qxQ7CkQ9kMzYjWZSNtrRZygHPDDqottzEJsqS4oUVodhW" crossorigin="anonymous"></script>
{% endblock script %}
{% block styles %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<link rel="stylesheet" href="{{ url_for('static', filename='css/custom.css', _external=True, _scheme='https') }}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Averia+Serif+Libre:ital@1&family=Montserrat:wght@500;700&display=swap" rel="stylesheet">
{% endblock styles %}
{% from "macros.html" import app_field, app_formfield %}
{% block body %}
<main>
    <div class="container-sm my-3">
        <div class="text-center mb-4">
            <div><img src="{{ url_for('static', filename='img/NewYork-Style.png', _external=True, _scheme='https') }}" alt="New York-Style" class="img-fluid" height="62" width="158"></div>
            <h1>Pizza Dough Calculator</h1>
        </div>
        <section class="row justify-content-center mb-5 no-print">
            <div class="col-md-9 col-lg-8 col-xl-6">
                <form action="" method="post" id="dough_calc" class="form-horizontal">
                    {{ form.hidden_tag() }}
                    <div class="form-group row text-center mb-4">
                        <ul id="choice" class="p-0 m-0">
                            {% for subfield in form.choice %}
                            <li class="form-check form-check-inline">
                                {{ subfield(class="form-check-input") }}
                                {{ subfield.label(class="form-check-label") }}
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div id="choice-wt" class="mb-0">
                        <div class="form-group row">
                            <div class="col-sm-4">
                                {{ form.dough_wt.label(class='control-label me-2') }}
                                <div class="d-inline-flex">
                                    <ul class="p-0 mb-0">
                                        {% for subfield in form.g_oz %}
                                        <li class="form-check form-check-inline">
                                            {{ subfield(class="form-check-input") }}
                                            {{ subfield.label(class="form-check-label oz-g") }}
                                        </li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>
                            <div class="col-sm-8 mb-4">
                                {{ form.dough_wt(class='form-control') }}
                            </div>
                        </div>
                    </div>
                    <div id="choice-tf" class="mb-3">
                        <div class="form-group row align-items-end mb-4">{{ form.thk_factor.label(class='control-label col-sm-4') }}<div class="col-sm-1 text-center"><output name="tf" for="thk_factor">0.09</output></div><div class="col-sm-7 d-inline-flex">{{ form.thk_factor(class='form-range slider', value=0.09, step=0.005) }}</div></div>
                        {{ app_field(form.pizza_size, class='form-control', value=16, step=1) }}
                    </div>
                    {{ app_field(form.pizza_num, class='form-control', value=1, step=1) }}
                    <div class="form-group row align-items-end mb-4">{{ form.water.label(class='control-label col-sm-4') }}<div class="col-sm-1 text-center"><output name="hydration" for="water">61%</output></div><div class="col-sm-7 d-inline-flex">{{ form.water(class='form-range slider', value=61, step=1) }}</div></div>
                    {{ app_formfield(form.yeast, class='form-control', value=0.5, step=0.05) }}
                    {{ app_field(form.salt, class='form-control', value=1.5, step=0.05) }}
                    {{ app_field(form.olive_oil, class='form-control', value=3, step=0.05) }}
                    {{ app_field(form.sugar, class='form-control', value=1.5, step=0.05) }}
                    <div class="col-sm-4 d-inline-flex" hx-target="this" hx-swap="outerHTML">
                        <button id="hx-add" class="btn btn-sm btn-outline-secondary col-auto my-1 me-2"
                                hx-get="{{ url_for('apps.add_ingredient', _external=True, _scheme='https') }}"
                                hx-trigger="click">Add Ingredient
                        </button>
                    </div>
                    <div class="col-sm-7 d-inline-flex justify-content-center">
                        {{ form.calculate(class='btn col-auto') }}
                    </div>
                </form>
            </div>
        </section>
        {% if dough %}
        <section class="row justify-content-center">
            <div class="table-responsive col-lg-6 mb-4" id="recipe">
                <table class="table table-hover">
                    <caption>New York-Style Pizza Dough Recipe</caption>
                    <thead class="table-dark">
                        <tr>
                            <th></th>
                            <th>Percent</th>
                            <th>Grams</th>
                            <th>Ounces</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for ingredient, amounts in dough.items() %}
                        <tr>
                            {% if ingredient in ('IDY', 'ADY') %}
                                <th>{{ ingredient }}</th>
                            {% else %}
                                <th>{{ ingredient.replace('_', ' ') | title }}</th>
                            {% endif %}
                            <td>{{ amounts['Percent'] | float | round(2) }}{{ '%' }}</td>
                            <td>{{ amounts['Grams'] | float | round(2) }}</td>
                            <td>{{ amounts['Ounces'] | float | round(2) }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                    <tfoot>
                        <tr>
                            <th>{{ 'Total' }}</th>
                            <td>{{ total['Percent'] | float | round(2) }}{{ '%' }}</td>
                            <td>{{ total['Grams'] | float | round(2) }}</td>
                            <td>{{ total['Ounces'] | float | round(2) }}</td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </section>
        {% else %}
        <div class="text-center mb-2 no-print">
            <img src="{{ url_for('static', filename='img/doughball.jpeg', _external=True, _scheme='https') }}" alt="pizza doughball" class="img-fluid">
        </div>
        {% endif %}
        <div class="text-center no-print">
            <button type="button" id="print" class="btn btn-outline-success mx-1" hidden>Print</button>
            <a class="btn btn-outline-dark" href="{{ url_for('home.index', _external=True, _scheme='https') }}">Home</a>
        </div>
        <!-- Bootstrap JavaScript Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    </div>
</main>
{% endblock body %}